
#!/usr/bin/env python
# encoding: utf-8

"""
waf build script for Lighttpd 2.x
License and Copyright: see COPYING file
"""

import Options, sys

source = '''
	actions.c
	angel.c
	angel_fake.c
	chunk.c
	chunk_parser.c
	collect.c
	condition.c
	config_parser.rl
	connection.c
	environment.c
	etag.c
	filter_chunked.c
	http_headers.c
	http_request_parser.rl
	http_response_parser.rl
	lighttpd-glue.c
	lighttpd.c
	log.c
	network.c
	network_sendfile.c
	network_write.c
	network_writev.c
	options.c
	plugin.c
	plugin_core.c
	profiler.c
	request.c
	response.c
	server.c
	stat_cache.c
	throttle.c
	url_parser.rl
	value.c
	virtualrequest.c
	worker.c
'''

def configure(conf):
	global source

	opts = Options.options

	if opts.lua:
		source += '''
			actions_lua.c
			condition_lua.c
			config_lua.c
			value_lua.c
		'''


def build(bld):
	opts = Options.options
	libs = ['glib', 'gthread', 'gmodule', 'ev']

	if opts.lua:
		libs += ['lua']

	libcommon = bld.new_task_gen(
		features = 'cc cprogram',
	 	source = source,
		defines = ['HAVE_CONFIG_H=1'],
		uselib = libs,
		uselib_local = ['common'],
		target = 'lighttpd')
