
#!/usr/bin/env python
# encoding: utf-8

"""
waf build script for Lighttpd 2.x
License and Copyright: see COPYING file
"""

import Options, sys, Utils

def configure(conf):
	pass


def build(bld):
	source = '''
		angel_connection.c
		angel_data.c
		buffer.c
		encoding.c
		idlist.c
		ip_parsers.rl
		mempool.c
		module.c
		radix.c
		utils.c
		waitqueue.c
	'''

	libcommon = bld.new_task_gen(
		features = 'cc cshlib',
	 	source = source,
		defines = ['HAVE_CONFIG_H=1'],
		uselib = ['glib', 'gthread', 'gmodule', 'ev'],
		includes = ['#/include/'],
		target = 'common')
