name: "Checks (macOS)"

on: [push, pull_request]

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

env:
  C_INCLUDE_PATH: /opt/homebrew/opt/libev/include
  LIBRARY_PATH: /opt/homebrew/opt/libev/lib

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pkgs=(
            meson
            libev
            ragel
            glib
            lua@5.4
            # zlib # keg-only
            # bzip2 # keg-only
            openssl@3
            gnutls
            libidn
            python3
            md5sha1sum
          )
          brew install "${pkgs[@]}"
      - name: python venv setup
        run: |
          python3 -m venv venv
          venv/bin/pip3 install pycurl
          venv/bin/python3 -c 'import pycurl'
      - name: meson setup
        run: meson setup -D unwind=false mesonbuilddir
      - name: meson compile
        run: meson compile -C mesonbuilddir
      - name: prepare environment for tests
        run: |
          sudo ifconfig lo0 alias 127.0.0.2 up

          # try to create a tmpdir with a short relative path (for shorter unix socket paths)
          NEWTMPDIR=~/tmp
          ln -sf "${TMPDIR}" "${NEWTMPDIR}"
          echo "TMPDIR=$NEWTMPDIR" >> "$GITHUB_ENV"
          echo "PATH=$(brew --prefix python)/libexec/bin:$PATH" >> "$GITHUB_ENV"

          if [ ! -f $(brew --prefix python)/libexec/bin/python3 ]; then
            # the brew path only provides "python", not "python3"...
            ln -s python $(brew --prefix python)/libexec/bin/python3
          fi
      - name: meson test
        run: |
          source venv/bin/activate
          meson test -C mesonbuilddir -v
